---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: litecoin
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: litecoin
  namespace: litecoin
spec:
  serviceName: litecoin
  replicas: 1
  selector:
    matchLabels:
      app: litecoin
  template:
    metadata:
      labels:
        app: litecoin
    spec:
      securityContext:
        runAsUser: 10001
      containers:
      - name: litecoin
        image: DOCKER_REPO/litecoin:0.18.1
        resources:
          requests:
            memory: 256Mi
          limits:
            cpu: 0.5
            memory: 256Mi
  volumeClaimTemplates:
  - metadata:
      name: litecoindata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi